Sprint#11. Add database
DmitriyVintov/java-filmorate pull request #10
Opened 2023-06-26 16:52 UTC by DmitriyVintov

2023-06-26 17:52 UTC, kirinichny commented
Диаграмма базы данных отличная, мне нечего добавить :)

2023-06-26 18:04 UTC, kirinichny reviewed
Диаграмма базы данных отличная, мне нечего добавить :)

2023-08-08 19:08 UTC, z8q requested changes

2023-08-08 19:08 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbFilmStorage.java
> +    public Film create(Film film) {
При отправке POST http://localhost:8080/films
```JSON
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"rating": 100,
	"duration": 1,
	"mpa": {
		"id": 1,
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [
		{
			"name": "action"
		},
		{
			"id": 2,
			"name": "drama"
		},
		{
			"id": 3,
			"name": "comedy"
		}
	]
}
```
В первом жанре пропущен id.

Получаю ошибку 500:
```JSON
{
	"error": "Произошла непредвиденная ошибка."
}
```
Но фильм при этом сохраняется

2023-08-08 19:08 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbFilmStorage.java
> +    public Film create(Film film) {
Если сделаю Put пустым полем name, вернется ошибка 500 `Произошла непредвиденная ошибка`
Можно было бы вернуть сообщение о том, что конкретное поле не заполнено.

Например, если попробовать сделать put с несуществующим id, ошибка будет такая
```JSON
{
	"error": "Фильма с id 2 не существует"
}
```
Можно было бы в таком же виде оформить

2023-08-08 19:08 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbUserStorage.java
> +    public User create(User user) {
При создании user тоже можно было бы обработать ошибки валидации и вернуть понятную причину.
Например
```JSON
{
	"email": "@yandex.ru",
	"login": "bobLogin",
	"name": "bob",
	"birthday": "2011-11-11"
}
```
Также вернет 500 `Произошла непредвиденная ошибка.`

2023-08-08 19:08 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbUserStorage.java
> +    public User create(User user) {
Если сделаю POST http://localhost:8080/users
```JSON
{
	"email": "bob@yandex.ru",
	"login": "bobLogin",
	"name": "bob",
	"birthday": "2011-11-11"
}
```
а потом добавлю еще одного пользователя, у которого изменю только email
```JSON
{
	"email": "bob2@yandex.ru",
	"login": "bobLogin",
	"name": "bob",
	"birthday": "2011-11-11"
}
```
То на второй запрос вернется код 200 с body
```JSON
{
	"id": null,
	"email": "bob2@yandex.ru",
	"login": "bobLogin",
	"name": "bob",
	"birthday": "2011-11-11",
	"friends": []
}
```
А в базе при этом сохранение не произойдет

2023-08-08 19:08 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbUserStorage.java
> +    public void addFriend(Integer userId, Integer friendId) {
Можно добавить самого себя в друзья

2023-08-08 19:08 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbUserStorage.java
> +    public void addFriend(Integer userId, Integer friendId) {
При повторном запросе код 500 `Произошла непредвиденная ошибка`

2023-08-08 19:08 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      @NotNull
notBlank проверяет на notNull, можно убрать

2023-08-08 19:08 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            System.out.println(e.getMessage());
Так обрабатывать ошибки не стоит.
Сообщение можно логировать log.error
Также можно бросить потом исключение

2023-08-08 19:08 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!userService.getUsers().contains(userService.getById(userId))) {
В контроллерах много логики, стоит оставить только логирование и вызов сервиса с возращением ответа.
Всю логику лучше перенести в класс сервиса

2023-08-11 03:32 UTC, z8q requested changes

2023-08-11 03:32 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
Аннотация осталась, логи в контроллере можно было бы оставить
log.info() что  например пришел запрос на создание/обновление/... с определенным id

2023-08-11 03:32 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
в userController тоже

2023-08-11 03:32 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      }
не сразу обратил внимание, в getFilms() идет обращение в базу для логов и потом для возвращаемого значения.
Можно было бы сократить количество вызовов, вызвать один раз, сохранить в переменную, и ее дальше использовать

2023-08-11 03:32 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateFilm(id);
тут тоже разберем
в validateFilm выполняется два вызова к базе:
`getFilms() -> filmStorage.getAll()`
`filmStorage.getById(id)`

и тут в 51-й строке `return filmStorage.getById(id);`
Хотя мы могли бы обратиться к базе один раз через filmStorage.getById(id) и проверить, что вернулось, на null
Если не найден – бросить исключение

2023-08-11 03:32 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Optional<User> userValidationEmail = getUsers().stream()
в этом методе много раз обращаемся к базе с getUsers, хотя могли бы один
Если будет время, можно попробовать реализовать правила через базу
например что-то такое:
`create unique index if not exists USER_EMAIL_UINDEX on USERS (email);`
или для группы колонок в таблице, как тут:
https://stackoverflow.com/questions/14221775/in-postgresql-force-unique-on-combination-of-two-columns

Но если не будет времени, через логику в коде тоже допустимо)

2023-08-12 16:30 UTC, z8q approved these changes

2023-08-12 17:39 UTC, merged