Sprint 9. Добавление контроллеров пользователей и фильмов
DmitriyVintov/java-filmorate pull request #2
Opened 2023-05-28 18:00 UTC by DmitriyVintov

2023-05-29 12:03 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ и видно, что хорошо проработан, отлично. 
После принятия к сведению комментариев, присылай работу на завершение проверки.
Спасибо.

2023-05-29 12:03 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Positive
Можно иначе:

Вариант, реализованный здесь корректен и удовлетворяет ТЗ, при этом в качестве аннотации можно также использовать @min(0) (или даже @Min(value = 0, message = "Продолжительность фильма не должна быть отрициательной")), а в качестве типа самой переменной - Period. При выборе того или иного решения всегда полезно знать альтернативы и понимать их плюсы и минусы примерные.

2023-05-29 12:03 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Validated
Можно лучше:

Насколько мне известно, аннотация `@Validated`  на уровне класса (class-level) нужна, если прямо в методах контроллера (а не в классах моделей) у параметров метода используются аннотации-ограничения вроде `@Min(5)` (см. некоторые детали этого, например, тут, https://reflectoring.io/bean-validation-with-spring-boot , со слов "Note that we have to add Spring’s @Validated annotation to the controller at class level to tell Spring to evaluate the constraint annotations on method parameters.").

Т.е. в данном случае, можно её удалить, т.к. есть независимые от неё аннотации @Valid на уровне параметров методов (которые, кстати, можно было бы заменить на @Validated, но это работает только в контроллерах, для методов сервисов, к примеру, работает только @Valid, а также @Valid может осуществлять валидацию иерархично, если один класс-модель с аннотациями-ограничениями используется в другом классе модели со своими аннотациями-ограничениями, см. некоторые детали этого, например, тут, https://www.baeldung.com/spring-valid-vs-validated , https://stackoverflow.com/a/65202134).

UPDATE: (увидел сейчас, что ты используешь маркерные интерфейсы в моделях Film и User) нужно у соответствующих методов указать перед валидируемыми параметрами такого рода аннотацию, чтобы она работала, см. пример тут, https://www.baeldung.com/spring-valid-vs-validated , со слов "In addition, we'll update our controller to use the @Validated annotation instead of @Valid:" (кстати, тогда также не нужна аннотация `@Validated`  на уровне класса):
```
@PostMapping()
    public User createUser(@Validated(Marker.OnCreate.class) @RequestBody User user) {
```

2023-05-29 12:03 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @MinimumDate("1895-12-28")
Отлично:

Отлично, что используешь здесь не только самые базовые аннотации для валидации (вроде @NotBlank, @NotNull) и круто, что реализовал свою аннотацию для проверки минимальной даты на базе @Constraint!

2023-05-29 12:03 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank
Можно лучше:

В соответствии с ТЗ логин не должен содержать пробелов ("внутри" текста), поэтому можно добавить эту проверку или в метод валидации контроллера, или, например, такой аннотацией над данным полем логина: `@Pattern(regexp = "\\S*", message = "Login should not include any blanks")`.

2023-05-29 12:03 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Slf4j
Отлично:

Отлично, что ты используешь здесь библиотеку slf4j для логирования и аннотацию @Slf4j библиотеки Lombok, чтобы не создавать логгер вручную!

2023-05-29 12:03 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film.setId(id);
Можно лучше:

Иногда бывает полезно логировать (на уровне debug или info) не только ошибки, но и успешное выполнение операций (с некоторыми их параметрами, вроде id, чтобы потом распознать, какие операции указаны в конкретном логе), но это сильно зависит от проекта, договорённостей внутри команды и возможностей хранения большого количества логов на серверах.

2023-05-29 12:03 UTC, zgreen3 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Set<ConstraintViolation<Film>> violations = validator.validate(film);
Отлично:

Отлично, что ты разобрался с возможностью запуска валидации независимо от контроллеров (с их аннотациями валидации, при этом такой тест уже связан непосредственно с классом модели Film и можно разместить в тестах для модели - в данном проекте это не принципиально, потому что тестов в целом пока не очень много и ориентироваться в них пока удобно в одном файле)!

2023-05-29 12:03 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Data
Отлично:

Отлично, что ты используешь здесь аннотацию `@Data` библиотеки Lombok, т.к. с ней нужно проделывать меньше работы по созданию сущностей =) (при этом такой подход - не панацея, т.к. у Lombok-а есть свои тонкие недостатки, например, рост времени компиляции приложений на порядок, если использовать ряд аннотаций Lombok, требующих от его препроцессора значительной работы и т.п., это стоит также иметь ввиду и уметь писать нужные методы руками, а также внимательно изучать документацию этой библиотеки для понимания, какой код она неявно привносит в приложение).

2023-05-29 12:56 UTC, DmitriyVintov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Positive
Хорошее замечание. Аннотацию исправил. Но возник вопрос. Зачем использовать Period для продолжительности фильма? Для минут же он не подойдет

2023-05-30 12:58 UTC, DmitriyVintov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Validated
Почему то с validated  не проходят api тесты в postman. Оставил как было

2023-05-30 14:16 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Positive
Насчёт невозможности учёта минут в Period согласен, про это я или не подумал, когда писал, или перепутал с Duration (тогда можно задавать время как раз в минутах, вроде `Duration.ofMinutes(120)`) - сейчас не вспомню, спасибо, что прокомментировал и молодец, что заметил!

2023-05-30 14:16 UTC, zgreen3 approved these changes
Привет, вижу, что ты учёл все важные комментарии, отлично! 
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.

2023-05-30 15:27 UTC, merged