Merge branch 'main' into 'develop'
DmitriyVintov/java-filmorate pull request #23
Opened 2023-09-03 17:58 UTC by DmitriyVintov

2023-09-04 18:28 UTC, z8q requested changes

2023-09-04 18:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +package ru.yandex.practicum.filmorate.controller;
Нужно будет еще в readme указать, какие задачи были выполнены

2023-09-04 18:28 UTC, z8q commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +//class FilmServiceTest {
Закомментировать тест не очень хорошо.
Можно либо убрать, либо аннотацию поставить над классом, для  junit5 - `@Disabled`
Если бы был junit4 - `@Ignore`

2023-09-04 18:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbUserEventStorage.java
> +public class DbUserEventStorage {
DbReviewStorage и DbUserEventStorage можно тоже реализовать через интерфейсы

2023-09-04 18:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review addReview(@RequestBody Review review) {
Можно сохранить ревью с заранее заданным полем useful.
POST http://localhost:8080/reviews
```JSON
{
    "content": "Like!",
    "isPositive": true,
    "userId": 1,
    "filmId": 1,
    "useful": 9999
}
```

2023-09-04 18:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void addLike(@PathVariable Integer id, @PathVariable Integer userId) {
Пользователь на свое ревью может поставить неограниченное количество лайков

2023-09-04 18:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbReviewStorage.java
> +    public Review addReview(Review review) {
Не удается удалить пользователя, который оставлял ревью.
Приходит ошибка 500:
```JSON
{
	"error": "Произошла непредвиденная ошибка."
}
```

2023-09-04 18:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbFilmStorage.java
При повторной попытке поставить лайк на фильм можно было бы бросать исключение. Присылать сообщение с ошибкой, что пользователь уже поставил лайк. Сейчас приходит ответ 200 на повторный лайк, но в базе остается одна запись. Что одна запись – это хорошо) Но вот feed засоряется повторными лайками

2023-09-04 18:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Director getDirector(@PathVariable int id) {
На несуществующего режиссера можно чуть подправить сообщение ошибки
GET http://localhost:8080/directors/123 выводит:
```JSON
{
	"error": "Режиссера с ID123нет в базе!"
}
```

2023-09-04 18:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    @Min(value = 1, message = "Значение id не может быть меньше 1")
Почему-то не могу добавить режиссера только с полем name
POST http://localhost:8080/directors
```JSON
{
	"name": "New director"
}
```
дает
```JSON
{
	"violations": [
		{
			"message": "Значение id не может быть меньше 1"
		}
	]
}
```
А если передам id в body, то все хорошо, но правда он не нужен, потому что логика в программе задает id.
```JSON
{
	"id": 1,
	"name": "New director"
}
```
ответ
```JSON
{
	"id": 5,
	"name": "New director"
}
```

2023-09-04 18:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film createFilm(@Valid @RequestBody Film film) {
Допускается создание дубликатов фильмов

2023-09-04 18:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getSortedFilmsByDirector(@PathVariable int directorId, @RequestParam String sortBy) {
Если создать режиссера и не привязать к нему фильм, то этот метод выдаст ошибку:
```JSON
{
	"error": "Такого режиссера нет!"
}
```
Хотя на самом деле режиссер есть, но у него нет фильмов

2023-09-05 19:54 UTC, DmitriyVintov commented
При фиксе повторного лайка падают тесты постман. Не устанавливается лайк фильму и поэтому не создается один event

2023-09-06 18:20 UTC, z8q requested changes

2023-09-06 18:20 UTC, z8q commented on src/main/resources/schema.sql
> +    film_id     integer not null,
Почему решили убрать референсы? 
Вроде бы по схеме er-diagram они остаются

2023-09-06 18:20 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbReviewStorage.java
> +    public Review create(Review review) {
Если переопределяем метод интерфейса, нужно помечать `@Override`, чтобы, если возникнут несоответствия с интерфейсом, например захотим здесь добавить второй аргумент, идея нам подсветит ошибку - метод не соответствует интерфейсу

2023-09-06 18:20 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/DbReviewStorage.java
> +        return null;
Почему решили не реализовывать?
Есть несколько опций:
- можно реализовать метод с корректной выдачей всех ревью
- можно в интерфейсе пометить этот метод как default, и в интерфейсе же в нем бросать исключение NotSupportedException,  а в имлпементациях переопределять, если нужно

Во втором случае, если этот метод захотят вызвать, получат понятное исключение, почему ничего не пришло

2023-09-06 18:20 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> collect = getFilms().stream().filter(film1 -> film1.getName().equals(film.getName())
Можно было бы выделить в отдельный метод

2023-09-07 18:26 UTC, z8q approved these changes
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде. Здорово, что решили выполнить не только обязательные задачи, но взяли и дополнительные. Правки сделали быстро, программа соответствует требованиям. Доработки принимаю)

2023-09-07 18:30 UTC, merged